IT'S SHOWTIME
TALK TO THE HAND "How many goats:"
HEY CHRISTMAS TREE isLessThan10
YOU SET US UP @NO PROBLEMO
HEY CHRISTMAS TREE goats
YOU SET US UP 0
STICK AROUND isLessThan10
GET TO THE CHOPPER goats
HERE IS MY INVITATION goats
GET UP 1
ENOUGH TALK
TALK TO THE HAND goats
GET TO THE CHOPPER isLessThan10
HERE IS MY INVITATION 10
LET OFF SOME STEAM BENNET goats
ENOUGH TALK
CHILL
TALK TO THE HAND "Goats everywhere."
YOU HAVE BEEN TERMINATED